### ISSUE TITLE
Why is LayerNorm default to False?

### ISSUE THREAD

**Issue by mathDR** [juho-lee/set_transformer#16]
Not an issue, but a question:  why is the default LayerNorm function set to False?  In particular, for the point cloud example, the LayerNorm is not used.

Can you comment on the importance of having the nested LayerNorm activated for the model?  That is, in the paper there was not exposition on having LayerNorm activated versus not.

Thanks!

**Comment by juho-lee** [comment]
For our experiments, we found LayerNorm not very effective so set False as our default option. But it depends on the problem you want to solve.

**Comment by mathDR** [comment]
Okay Great.  So it sounds like `False` is a good default for your experiments.  Thanks for the clarification!
